# Generated by Django 5.1.7 on 2025-05-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_freetogame_profile_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
