# Generated by Django 5.1.7 on 2025-05-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='marca', max_length=100),
            preserve_default=False,
        ),
    ]
