# Generated by Django 5.1.7 on 2025-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="font_size",
            field=models.CharField(default="12px", max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="font_type",
            field=models.CharField(default="Arial", max_length=50),
        ),
    ]
