# Generated by Django 5.1.7 on 2025-05-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_validpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validpassword',
            name='value',
            field=models.TextField(unique=True),
        ),
    ]
