# Generated by Django 5.1.7 on 2025-05-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0012_alter_validpassword_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
