# Generated by Django 5.1.7 on 2025-05-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_alter_comment_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="font_size",
            field=models.CharField(default="18px", max_length=10),
        ),
    ]
