# Generated by Django 5.1.7 on 2025-05-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='freetogame_profile_url',
            field=models.URLField(default='https://default.url', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_url',
            field=models.URLField(default='https://default.url', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.URLField(default='https://google', max_length=500),
            preserve_default=False,
        ),
    ]
